
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'
gem 'sqlite3'
gem 'rerun'
gem 'bcrypt'
gem 'pony'
gem 'dotenv'
gem 'stripe'                                        
    
